# سوال۱

الگوریتم های SVM از مجموعه ای از توابع ریاضی که به عنوان کرنل تعریف می شوند، استفاده می کنند. وظیفه کرنل این است که داده ها را به عنوان ورودی گرفته و آن ها را به شکل مورد نیاز تبدیل کند. الگوریتم های مختلف SVM ، از انواع مختلف توابع کرنل استفاده می کنند. این توابع می توانند انواع متفاوتی داشته باشند. به عنوان مثال خطی ،  غیرخطی ، چند جمله ای ، تابع پایه شعاعی (RBF) و سیگموئید. 
توابع کرنل ، برای داده های ترتیبی ، نمودار ها ، متن ها ، تصاویر و همچنین بردار ها معرفی می شوند. پرکاربردترین نوع تابع کرنل، RBF است. زیرا دارای پاسخ محلی و متناهی در کل بازه محور x است.
توابع کرنل ، ضرب داخلی بین دو نقطه در یک فضای ویژگی مناسب را برمی گردانند. بنابراین ، با هزینه محاسباتی کم، حتی در فضاهای با ابعاد بالا، مفهومی از شباهت را تعریف می کنند.

# سوال 2

In [154]:
import pandas as pd
from sklearn.svm import SVC 
from sklearn.metrics import classification_report
from pandas.api.types import CategoricalDtype
from sklearn.model_selection import train_test_split

In [178]:
X = pd.read_csv('dataset/train.csv').to_numpy()[:,:-1]
y = pd.read_csv('dataset/train.csv').to_numpy()[:,-1].astype(int)

train_X, test_X, train_y, test_y = train_test_split(X, y, test_size=0.2, random_state=42)

In [179]:
clf = SVC(kernel='rbf')
clf.fit(train_X, train_y)

y_pred = clf.predict(test_X)
print(classification_report(test_y, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.98      0.99       105
           1       0.95      0.99      0.97        91
           2       0.94      0.95      0.94        92
           3       0.98      0.95      0.96       112

    accuracy                           0.96       400
   macro avg       0.96      0.97      0.96       400
weighted avg       0.97      0.96      0.97       400

# سوال۳

In [180]:
clf = SVC(kernel='linear',gamma='auto')
clf.fit(train_X, train_y)

y_pred = clf.predict(test_X)
print(classification_report(test_y, y_pred))

              precision    recall  f1-score   support

           0       1.00      0.94      0.97       105
           1       0.91      1.00      0.95        91
           2       0.99      0.95      0.97        92
           3       0.98      0.99      0.99       112

    accuracy                           0.97       400
   macro avg       0.97      0.97      0.97       400
weighted avg       0.97      0.97      0.97       400

In [181]:
clf = SVC(kernel='linear',gamma='scale')
clf.fit(train_X, train_y)

y_pred = clf.predict(test_X)
print(classification_report(test_y, y_pred))

              precision    recall  f1-score   support

           0       1.00      0.94      0.97       105
           1       0.91      1.00      0.95        91
           2       0.99      0.95      0.97        92
           3       0.98      0.99      0.99       112

    accuracy                           0.97       400
   macro avg       0.97      0.97      0.97       400
weighted avg       0.97      0.97      0.97       400

In [182]:
clf = SVC(kernel='poly',gamma='scale')
clf.fit(train_X, train_y)

y_pred = clf.predict(test_X)
print(classification_report(test_y, y_pred))

              precision    recall  f1-score   support

           0       0.97      0.99      0.98       105
           1       0.95      0.97      0.96        91
           2       0.96      0.92      0.94        92
           3       0.97      0.96      0.97       112

    accuracy                           0.96       400
   macro avg       0.96      0.96      0.96       400
weighted avg       0.96      0.96      0.96       400

In [183]:
clf = SVC(kernel='rbf',gamma='scale')
clf.fit(train_X, train_y)

y_pred = clf.predict(test_X)
print(classification_report(test_y, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.98      0.99       105
           1       0.95      0.99      0.97        91
           2       0.94      0.95      0.94        92
           3       0.98      0.95      0.96       112

    accuracy                           0.96       400
   macro avg       0.96      0.97      0.96       400
weighted avg       0.97      0.96      0.97       400

# سوال۴

In [184]:
#soft margin
clf = SVC(C=2)
clf.fit(train_X, train_y)

y_pred = clf.predict(test_X)
print(classification_report(test_y, y_pred))

              precision    recall  f1-score   support

           0       1.00      0.98      0.99       105
           1       0.94      1.00      0.97        91
           2       0.93      0.93      0.93        92
           3       0.98      0.95      0.96       112

    accuracy                           0.96       400
   macro avg       0.96      0.97      0.96       400
weighted avg       0.97      0.96      0.97       400

In [185]:
#hard margin
clf = SVC(C=0.01)
clf.fit(train_X, train_y)

y_pred = clf.predict(test_X)
print(classification_report(test_y, y_pred))

              precision    recall  f1-score   support

           0       1.00      0.47      0.64       105
           1       0.50      0.98      0.66        91
           2       0.46      0.67      0.55        92
           3       1.00      0.35      0.52       112

    accuracy                           0.60       400
   macro avg       0.74      0.62      0.59       400
weighted avg       0.76      0.60      0.59       400

#  aسوال۵

In [357]:
df = pd.read_csv('dataset/train.csv')

min_value = df['battery_power'].min()
max_value = df['battery_power'].max()
print(min_value)
print(max_value)

501
1998

In [358]:
import numpy as np
bins = np.linspace(min_value,max_value,4)
labels = [0, 1, 2]
df['battery_power'] = pd.cut(df['battery_power'], bins=bins, labels=labels, include_lowest=True)

In [359]:
df

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,...,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi,price_range
0,0,0,2.2,0,1,0,7,0.6,188,2,...,20,756,2549,9,7,19,0,0,1,1
1,1,1,0.5,1,0,1,53,0.7,136,3,...,905,1988,2631,17,3,7,1,1,0,2
2,0,1,0.5,1,2,1,41,0.9,145,5,...,1263,1716,2603,11,2,9,1,1,0,2
3,0,1,2.5,0,0,0,10,0.8,131,6,...,1216,1786,2769,16,8,11,1,0,0,2
4,2,1,1.2,0,13,1,44,0.6,141,2,...,1208,1212,1411,8,2,15,1,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,0,1,0.5,1,0,1,2,0.8,106,6,...,1222,1890,668,13,4,19,1,1,0,0
1996,2,1,2.6,1,0,0,39,0.2,187,4,...,915,1965,2032,11,10,16,1,1,1,2
1997,2,0,0.9,1,1,1,36,0.7,108,8,...,868,1632,3057,9,1,5,1,1,0,3
1998,2,0,0.9,0,4,1,46,0.1,145,5,...,336,670,869,18,10,19,1,1,1,0
1999,0,1,2.0,1,5,1,45,0.9,168,6,...,483,754,3919,19,4,2,1,1,1,3

#  bسوال۵

In [360]:
df["battery_power"].astype(CategoricalDtype([0,1,2]))

0       0
1       1
2       0
3       0
4       2
       ..
1995    0
1996    2
1997    2
1998    2
1999    0
Name: battery_power, Length: 2000, dtype: category
Categories (3, int64): [0, 1, 2]

In [361]:
def OneHot(inp,maximum):
    li =  ['0']* maximum
    li[inp] = '1'
    return (''.join(li))

In [362]:
df["battery_power"] = df["battery_power"].apply(lambda x : OneHot(x,df['battery_power'].max()+1))
df["blue"] = df["blue"].apply(lambda x : OneHot(x,df['blue'].max()+1))
df["dual_sim"] = df["dual_sim"].apply(lambda x : OneHot(x,df['dual_sim'].max()+1))
df["four_g"] = df["four_g"].apply(lambda x : OneHot(x,df['four_g'].max()+1))
df["wifi"] = df["wifi"].apply(lambda x : OneHot(x,df['wifi'].max()+1))

In [363]:
df

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,...,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi,price_range
0,100,10,2.2,10,1,10,7,0.6,188,2,...,20,756,2549,9,7,19,0,0,01,1
1,010,01,0.5,01,0,01,53,0.7,136,3,...,905,1988,2631,17,3,7,1,1,10,2
2,100,01,0.5,01,2,01,41,0.9,145,5,...,1263,1716,2603,11,2,9,1,1,10,2
3,100,01,2.5,10,0,10,10,0.8,131,6,...,1216,1786,2769,16,8,11,1,0,10,2
4,001,01,1.2,10,13,01,44,0.6,141,2,...,1208,1212,1411,8,2,15,1,1,10,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,100,01,0.5,01,0,01,2,0.8,106,6,...,1222,1890,668,13,4,19,1,1,10,0
1996,001,01,2.6,01,0,10,39,0.2,187,4,...,915,1965,2032,11,10,16,1,1,01,2
1997,001,10,0.9,01,1,01,36,0.7,108,8,...,868,1632,3057,9,1,5,1,1,10,3
1998,001,10,0.9,10,4,01,46,0.1,145,5,...,336,670,869,18,10,19,1,1,01,0
1999,100,01,2.0,01,5,01,45,0.9,168,6,...,483,754,3919,19,4,2,1,1,01,3

این روش کدبندی  یکی از پرکاربردترین رویکردها است و عملکرد آن به جز در مواردی که متغیر دست ای مقادیر خیلی زیادی بگیرد، بسیار خوب است (معمولا از این روش برای متغیرهایی که بیش‌تر از ۱۵ مقدار متفاوت بگیرند، مناسب نیست.

#  cسوال۵

In [364]:
from sklearn.preprocessing import FunctionTransformer
transformer = FunctionTransformer(np.log1p, validate=True)
X = transformer.transform(df)

#  dسوال۵

In [365]:
df['aria'] = df['px_height'] *df['px_width']

In [366]:
df['aria']

0         15120
1       1799140
2       2167308
3       2171776
4       1464096
         ...
1995    2309580
1996    1797975
1997    1416576
1998     225120
1999     364182
Name: aria, Length: 2000, dtype: int64

# سوال۶

In [367]:
df= df[['battery_power',
  'blue',
  'clock_speed',
  'dual_sim',
  'fc',
  'four_g',
  'int_memory',
  'm_dep',
  'mobile_wt',
  'n_cores',
  'pc',
  'px_height',
  'px_width',
  'ram',
  'sc_h',
  'sc_w',
  'talk_time',
  'three_g',
  'touch_screen',
  'wifi',
  'price_range']]

In [368]:
#X = df.to_numpy()[:,:-1]
y = df.to_numpy()[:,-1].astype(int)
train_X, test_X, train_y, test_y = train_test_split(X, y, test_size=0.2, random_state=42)

In [369]:
clf = SVC(kernel='rbf')
clf.fit(train_X, train_y)

y_pred = clf.predict(test_X)
print(classification_report(test_y, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       105
           1       1.00      1.00      1.00        91
           2       0.87      0.99      0.92        92
           3       0.99      0.88      0.93       112

    accuracy                           0.96       400
   macro avg       0.96      0.97      0.96       400
weighted avg       0.97      0.96      0.96       400